### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by joncalhoun**
Added the book Web Development with Go by Jonathan Calhoun (@joncalhoun)

### CODE REVIEW

**Comment by joncalhoun** [comment]
I originally had a redirect because I intend to create my own landing page. I reverted back to linking directly to gumroad for now, but I will have to update this again later when I redo the landing page. Is that okay?

**Comment by joncalhoun** [comment]
I'm also not sure what the issue is with the link to the book cover. @dariubs Any idea what I can do to fix it?

**Comment by nathany** [comment]
@joncalhoun If I link to http://early.usegolang.com/images/Cover300ppi.png , I get a 401 authorization required error. Try opening it in incognito/private browsing in case you're already logged in. Maybe you can host it somewhere that is publicly accessible?

The linter is also complaining about duplicate links -- which I'm not sure why that is something it checks.

**Comment by joncalhoun** [comment]
Oh I completely forgot I have basic auth on that server since most files
aren't you license yet. I'll fix it and update the PR. Sorry about that!

**Comment by joncalhoun** [comment]
Should be good to go now. Sorry about the troubles!

**Comment by nathany** [comment]
No worries. Thanks.

**Pull request merged**
