### PR TITLE
remove download links for Webapps in Go

### LINKED ISSUE #40: Remove Build Webapps in Go Download links
The book is no longer available to download: https://github.com/dariubs/GoBooks#build-webapps-in-go-the-anti-textbook-free

* https://www.gitbook.com/download/pdf/book/thewhitetulip/webapp-with-golang-anti-textbook
* https://www.gitbook.com/download/epub/book/thewhitetulip/webapp-with-golang-anti-textbook
* https://www.gitbook.com/download/mobi/book/thewhitetulip/webapp-with-golang-anti-textbook

> 404
Not Found
E-Books downloads have been disabled for this book

### PR DESCRIPTION
**Pull request by nathany**
downloads are now $ at https://leanpub.com/antitextbookGo/ (linked from the GitHub repo, which still provides access to a free version)

fixes #40

/cc @thewhitetulip

### CODE REVIEW

**Comment by nathany** [comment]
@thewhitetulip I'm going to go ahead and merge this to get the build working again. Feel free to open a new pull request with further changes.

**Comment by thewhitetulip** [comment]
@nathany This looks good, although we can add a link to the leanpub version on the page itself, I didn't add it because it is not free, if you are okay with it, then I'll submit a PR.

**Comment by nathany** [comment]
@thewhitetulip If we add the Leanpub link, I'm not sure if we should state that it's free, or sort it above the non-free titles.

Curious what opinion @dariubs has on the matter.

**Comment by thewhitetulip** [comment]
True, let @dariubs reply and then I'll give a PR

**Pull request merged**
