### PR TITLE
added a new book

### PR DESCRIPTION
**Pull request by thewhitetulip**
added https://github.com/thewhitetulip/web-dev-golang-anti-textbook to the list of books

### CODE REVIEW

**Comment by appleboy** [comment]
:+1: nice book.

**Comment by thewhitetulip** [comment]
Hey @appleboy Thank you! :) 
I am still working on it, I plan to finish it soon, since the [Tasks](http://github.com/thewhitetulip/Tasks) app which spurred the book is almost over!

**Comment by appleboy** [comment]
@thewhitetulip [Tasks](https://github.com/thewhitetulip/Tasks) is an awesome repo. I already started it.

**Comment by thewhitetulip** [comment]
@appleboy Thank you very much :-) The application is ready for the most parts, only implementing AJAX on everything is left.

**Comment by dariubs** [comment]
Nice job. Thank you @thewhitetulip

**Comment by thewhitetulip** [comment]
@dariubs Thanks!!

**Pull request merged**
