### PR TITLE
add: go persian online/offline book

### PR DESCRIPTION
**Pull request by Ja7ad**

### CODE REVIEW

**Comment by Ja7ad** [comment]
> Thanks. Would you mind splitting this out by language? See the discussion in #47

Yw, No please.

**Comment by nathany** [comment]
Even just indicating the language might be a good option. 

Thoughts @dariubs?

**Comment by Ja7ad** [comment]
> Even just indicating the language might be a good option. 
> 
> Thoughts @dariubs?

I think don't split books, better use ToC

.
├── English/
│   ├── Free
│   ├── ...
│   ├── Paid
│   └── ...
├── Germany/
│   ├── Free
│   ├── ...
│   ├── Paid
│   └── ...
├── ...
├── Persian/
│   ├── Free
│   ├── ...
│   ├── Paid
│   └── ...
└── ...

**Comment by dariubs** [comment]
> Even just indicating the language might be a good option. 
> 
> Thoughts @dariubs?

I agree with adding new languages, but this list would be too long for all languages in one file, I think we should create separate files for each language we add and ask the contributors of that language to add their books and descriptions in their own language. And give a link to each language file in the main file.
In this case, it will be easy for users of that language to find books in their own language in search engines.
what do you think?

**Comment by Ja7ad** [comment]
> > Even just indicating the language might be a good option.
> > Thoughts @dariubs?
> 
> I agree with adding new languages, but this list would be too long for all languages in one file, I think we should create separate files for each language we add and ask the contributors of that language to add their books and descriptions in their own language. And give a link to each language file in the main file. In this case, it will be easy for users of that language to find books in their own language in search engines. what do you think?

No idea for this PR?

**Pull request merged**
